completeUpload = "`%s` upload completed, time consuming `%d s`,average upload speed `%s/s`"
configCreateSuccess = "The registration is successful. A new login file has been created in the running directory:`%s`"
existSkip = "Already exists, auto skip"
failToLink = "OneDrive account `%s` \n There was a connection problem when uploading `%s` Retrying, this is the %d times retrying"
failToLoadFiles = "Failed to Load Files from source :%v"
failToStore = "Failed to Restore :%v"
filenameFail = "`%s` The file name has illegal characters and cannot be uploaded, please modify it and re-upload, it has been automatically skipped"
googleDriveGetAccess = "Please open the following website, log in to Google account, copy the code according to the prompts on the page, paste it below and enter\nNote: This program does not involve your private information, please feel free to use it.\n%s\n"
googleDriveOAuthFileCreateSuccess = "Google Drive OAuth2 file created successfully, save to:"
googleDriveUploadTip = "Google Drive account `%s` \n Uploading `%s` Time: %d s"
googleDriveUploadTip1 = "Google Drive account `%s` \nUploading `%s`\nSize:`%s` Complete: `%s` Progress: *『%d/%d』*  \nSpeed:`%s` \nTime: `%d s`"
oneDriveBigFile = "File: `%s` Start upload to OneDrive\nAccounts:`%s`\nFile over 4MB, go to large file channel"
oneDriveSmallFile = "File: `%s` Start upload to OneDrive\nAccounts:`%s`\nFile less than 4MB, go to small file channel, uploading in progress"
oneDriveUploadTip1 = "OneDrive account `%s` \nUploading `%s`\nSize:`%s` Complete: `%s` Progress: *『%d/%d』*  \nSpeed:`%s/s` \nTime: `%d s`"
oneDriveUploadTip2 = "OneDrive account `%s` \nUploading `%s`\nSize:`%s` Complete: `%s` Progress: *『%d/%d』*  \nSpeed:`----` \nTime: `%d s`"
startToUpload = "`%s` start uploading, size:`%s`"
startToUpload1 = "start uploading to OneDrive"
startToUploadGoogleDrive = "start uploading to Google Drive"
startUploadGoogleDrive = "Start uploading to Google Drive"
telegramSendError = "Telegram Send Error:%s"
uploadGoogleDriveComplete = "Target item upload to Google Drive complete"
