name: JD BeanChange

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies And Run
        run: |
          cd scripts/
          npm install
          node jd_bean_change_new.js
          # node jd_bean_change.js
        env:
          TZ: Asia/Shanghai
          QMSG_KEY: e6f2c5b0021c68f8c70f98219954e717
          QMSG_MODE: group
          JD_COOKIE: ${{ secrets.JD_COOKIE3 }}
          TG_BOT_TOKEN: 1949709459:AAGP8xZlLtJCd_coJ8l_o4PF0OVxX1imfQw
          TG_USER_ID: 799728773
