name: JD_BeanChange

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          wget https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/package.json
          npm install

      - name: JD BeanChange
        run: |
          node jd_bean_change.js
        env:
          TZ: Asia/Shanghai
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_PLUS_TOKEN: b58b3b08d7b14fdfb3205934495a9905
