name: JD_JxgcTuan

on:
  workflow_dispatch:
  schedule:
    - cron: "40,46,52 15 * * *" # 08:00 -> 16:20  07:40 -> 16:00 15:40 -> 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: JD JxgcTuan
        run: |
          # wget https://raw.githubusercontent.com/JaimeZeng/MyActions/main/jd_jxgc_tuan.py
          python3 -m pip install requests
          python3 jd_jxgc_tuan.py
        env:
          TZ: Asia/Shanghai
          JD_COOKIE: ${{ secrets.JD_COOKIE1 }}
          PUSH_PLUS_TOKEN: b58b3b08d7b14fdfb3205934495a9905
