name: JD_QJD

on:
  workflow_dispatch:
  schedule:
    - cron: "0,1,3,5 0 * * *"

env:
  TZ: Asia/Shanghai
  JD_COOKIE: ${{ secrets.JD_COOKIE1 }}
  PUSH_PLUS_TOKEN: b58b3b08d7b14fdfb3205934495a9905

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: JD QJD
        run: |
          wget https://raw.githubusercontent.com/curtinlv/JD-Script/main/jd_qjd.py
          sed -e "s|'Your JD_User', '买买买'|'jd_5f9bd8e786798', 'Ryanjiena', 'RyanjienatxX', 'jd_JsMOGnzpJDPw', 'jd_QbKFesrCcBOn', 'jd_jACaJtmYXgCQ'|g" -i.bak jd_qjd.py
          python3 -m pip install requests
          python3 jd_qjd.py
