name: JD QJD

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "40 15,3 * * *" # 08:00 -> 16:20  07:40 -> 16:00 15:40 -> 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: JD QJD
        run: |
          wget https://raw.githubusercontent.com/curtinlv/JD-Script/main/jd_qjd.py
          sed -e "s|'Your JD_User', '买买买'|'jd_5f9bd8e786798', 'Ryanjiena', 'RyanjienatxX', 'jd_JsMOGnzpJDPw', 'jd_QbKFesrCcBOn', 'jd_jACaJtmYXgCQ'|g" -i.bak jd_qjd.py
          python3 -m pip install requests
          python3 jd_qjd.py
        env:
          TZ: Asia/Shanghai
          QQ_MODE: send
          QQ_SKEY: e6f2c5b0021c68f8c70f98219954e717
          JD_COOKIE: ${{ secrets.JD_COOKIE1 }}
          PUSH_PLUS_TOKEN: b58b3b08d7b14fdfb3205934495a9905
