name: Mi Motion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # 16:00 -> 00:00

env:
  TZ: Asia/Shanghai
  MI_USER: ${{ secrets.MI_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Mi Motion
        run: |
          cd scripts/
          pip3 install requests
          export MI_USER="${{ secrets.MI_USER }}"  
          export MI_PWD="3v4JEuVRYyb3Eh#WCaRTLppj2YTKU"  
          export STEP="24000-24888"  
          export PMODE="tg" 
          export PKEY="1904539307:AAFzLkpxpalwsNd0ArGBJB46im-M07ALtkE@799728773"
          python3 mimotion.py
