name: Update Script File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,10,16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Create local changes
        run: |
          cd conf/
          curl -s --connect-timeout 3 -O https://raw.githubusercontent.com/Oreomeow/VIP/main/Conf/Qinglong/config.sample.sh
          curl -s --connect-timeout 3 -o code.sample.sh https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/sh/Helpcode2.8/code.sh
          cd ../checkin/
          curl -s --connect-timeout 3 -O https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/py/netease.py

          cd ../jd_scripts/
          curl -O https://raw.githubusercontent.com/smiek2221/scripts/master/gua_wealth_island_help.js
          curl -o gua_wealth_island.js https://raw.githubusercontent.com/jiulan/platypus/main/scripts/jd_cfd_new.js
          curl -O https://raw.githubusercontent.com/jiulan/platypus/main/scripts/jd_all_bean_change.js
          curl -O https://raw.githubusercontent.com/shufflewzc/faker2/main/jd_bean_change_new.js
          curl -O https://raw.githubusercontent.com/yuannian1112/jd_scripts/main/jd_bean_change.js
          curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jd_ccSign.js
          curl -o jd_dreamFactory_tuan.js https://raw.githubusercontent.com/star261/jd/main/scripts/star_dreamFactory_tuan.js 
          curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jd_jxlhb.js
          curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jd_jxmc.js
          curl -O https://raw.githubusercontent.com/yuannian1112/jd_scripts/main/jd_redPacket.js
          curl -O https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/py/mimotion.py
          curl -O https://raw.githubusercontent.com/shufflewzc/faker2/main/package.json
          curl -O https://raw.githubusercontent.com/yuannian1112/jd_scripts/main/USER_AGENTS.js
          curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jx_sign.js
          sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i *.js
          sed -e "/if (JSON.stringify(process.env).indexOf('GITHUB') > -1) process.exit(0);/d" -i jd_redPacket.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i gua_wealth_island_help.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i gua_wealth_island.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i jd_all_bean_change.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i jd_bean_change.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i jd_dreamFactory_tuan.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i jd_jxmc.js
          # sed -e 's|"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);||g' -i jx_sign.js
      - name: Commit files
        run: |
          git config --local user.email "78083448+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # git commit -am "Add changes."
          git add .
          git commit -m "Add changes."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        run: |
          PUSH_TMP_PATH="./action.tmp"
          apt-get install jq -y
          file=$(git log -1 --name-status --format='') 
          message="## MyActions Update!\n\n"
          message="${message}- 提交者: $(git log -1 --pretty=format:'%cn')\n" 
          message="${message}- 提交时间: $(git log -1 --pretty=format:'%ci')\n" 
          message="${message}- 提交哈希值: $(git log -1 --pretty=format:'%H')\n" 
          message="${message}- 提交变动文件: $(file)\n" 
          if [ "${QMSG_KEY}" ]; then
              echo -e "msg=${result_qmsg_log_text}" >>${PUSH_TMP_PATH}
              push=$(curl http://wxpusher.zjiecode.com/api/send/message -X POST -d '{"appToken":"{WP_APP_TOKEN}","content":"${message}","contentType":"3", "topicIds":["${WP_TOPICIDS}"] }' -H "Content-Type: application/json" --silent)
              push_code=$(echo ${push} | jq -r "1000" 2>&1)
              if [ "${push_code}" -eq 0 ]; then
                  echo -e "WxPusher 发送通知消息: 成功"
              else
                  echo -e "WxPusher 发送通知消息: 失败"
              fi
          fi        
        env:
          TZ: Asia/Shanghai
          WP_APP_TOKEN: ${{ secrets.WP_APP_TOKEN }}
          WP_TOPICIDS: 2897
