name: Update Chrome Extensions

on:
  workflow_dispatch:
  schedule:
    # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
    # https://crontab.guru/
    - cron: "6 0 * * 0,2,5"

env:
  TZ: Asia/Shanghai
  tg_user_id: ${{ secrets.TG_USER_ID }}
  tg_bot_token: ${{ secrets.TG_BOT_TOKEN }}
  config_json: ${{ secrets.CONFIG_JSON }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Create local changes
        run: |
          cd update/
          sudo apt install jq curl wget -y
          echo ${config_json} >config.json
          bash update_chrome_extensions.sh >update.log
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_USER_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message_file: update.log
