name: Wealth_Island

on:
  workflow_dispatch:
  schedule:
    - cron: "1,16,31,46 17-23,0-16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10"]
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies And Run
        run: |
          cd scripts/
          npm install
          node gua_wealth_island.js
        env:
          TZ: Asia/Shanghai
          JD_COOKIE: ${{ secrets.JD_COOKIE }}